const dicionarioCapitais = {
    // África
    "Abuja": "Abuja",
    "Accra": "Acra",
    "Algiers": "Argel",
    "Antananarivo": "Antananarivo",
    "Cairo": "Cairo",
    "Dakar": "Dacar",
    "Khartoum": "Cartum",
    "Kinshasa": "Kinshasa",
    "Luanda": "Luanda",
    "Lusaka": "Lusaka",
    "Maputo": "Maputo",
    "Mogadishu": "Mogadíscio",
    "Monrovia": "Monróvia",
    "Nairobi": "Nairóbi",
    "Nouakchott": "Nouakchott",
    "Gaborone": "Gaborone",
    "Yamoussoukro": "Iamussucro",
    "Praia": "Praia",
    "Banjul": "Banjul",
    "Maseru": "Maseru",
    "Lilongwe": "Lilongue",
    "Port Louis": "Port Louis",
    "Windhoek": "Windhoek",
    "Niamey": "Niamei",
    "São Tomé": "São Tomé",
    "Mbabane": "Mbabane",
    "Tunis": "Tunes",
    "Tripoli": "Trípoli",

    // Américas
    "Brasília": "Brasília",
    "Buenos Aires": "Buenos Aires",
    "Caracas": "Caracas",
    "La Paz": "La Paz",
    "Ottawa": "Ottawa",
    "Panama City": "Cidade do Panamá",
    "Washington, D.C.": "Washington, D.C.",
    "Mexico City": "Cidade do México",
    "Quito": "Quito",
    "Santiago": "Santiago",
    "Bogotá": "Bogotá",
    "Havana": "Havana",
    "San José": "San José",
    "San Salvador": "San Salvador",
    "Santo Domingo": "Santo Domingo",
    "Montevideo": "Montevidéu",
    "Belmopan": "Belmopan",
    "Georgetown": "Georgetown",
    "Paramaribo": "Paramaribo",
    "Saint John's": "Saint John's",
    "Castries": "Castries",
    "Bridgetown": "Bridgetown",
    "Kingstown": "Kingstown",
    "Roseau": "Roseau",
    "Basseterre": "Basseterre",
    "Port of Spain": "Porto de Espanha",

    // Ásia
    "Abu Dhabi": "Abu Dhabi",
    "Amman": "Amã",
    "Baghdad": "Bagdá",
    "Baku": "Baku",
    "Bangkok": "Bangkok",
    "Beijing": "Pequim",
    "Beirut": "Beirute",
    "Damascus": "Damasco",
    "Dhaka": "Daca",
    "Doha": "Doha",
    "Hanoi": "Hanói",
    "Islamabad": "Islamabad",
    "Jakarta": "Jacarta",
    "Jerusalem": "Jerusalém",
    "Kabul": "Cabul",
    "Kampala": "Campala",
    "Kathmandu": "Catmandu",
    "Kyiv": "Kiev",
    "Kuala Lumpur": "Kuala Lumpur",
    "Kuwait City": "Cidade do Kuwait",
    "Malé": "Malé",
    "Naypyidaw": "Naypyidaw",
    "Vientiane": "Vientiane",
    "Bandar Seri Begawan": "Bandar Seri Begawan",
    "Sri Jayawardenepura Kotte": "Sri Jayawardenepura Kotte",
    "Dili": "Díli",
    "Ulaanbaatar": "Ulan Bator",
    "Ashgabat": "Asgabate",
    "Astana": "Astana",
    "New Delhi": "Nova Deli",
    "Pyongyang": "Pyongyang",
    "Riyadh": "Riade",
    "Seoul": "Seul",
    "Singapore": "Singapura",
    "Tehran": "Teerã",
    "Tokyo": "Tóquio",
    "Tbilisi": "Tbilisi",
    "Tashkent": "Tashkent",
    "Thimphu": "Thimphu",

    // Europa
    "Amsterdam": "Amsterdã",
    "Ankara": "Ancara",
    "Athens": "Atenas",
    "Belgrade": "Belgrado",
    "Berlin": "Berlim",
    "Bern": "Berna",
    "Bratislava": "Bratislava",
    "Brussels": "Bruxelas",
    "Bucharest": "Bucareste",
    "Budapest": "Budapeste",
    "Copenhagen": "Copenhague",
    "Dublin": "Dublin",
    "Helsinki": "Helsinque",
    "Lisbon": "Lisboa",
    "Ljubljana": "Liubliana",
    "London": "Londres",
    "Madrid": "Madri",
    "Minsk": "Minsk",
    "Moscow": "Moscou",
    "Nicosia": "Nicósia",
    "Oslo": "Oslo",
    "Paris": "Paris",
    "Prague": "Praga",
    "Riga": "Riga",
    "Rome": "Roma",
    "San Marino": "San Marino",
    "Sarajevo": "Sarajevo",
    "Skopje": "Escópia",
    "Sofia": "Sófia",
    "Stockholm": "Estocolmo",
    "Tallinn": "Tallinn",
    "Tirana": "Tirana",
    "Vaduz": "Vaduz",
    "Valletta": "Valeta",
    "Vienna": "Viena",
    "Vilnius": "Vilnius",
    "Warsaw": "Varsóvia",
    "Zagreb": "Zagreb",
    "Andorra la Vella": "Andorra-a-Velha",
    "Monaco": "Mônaco",
    "Chişinău": "Quixinau",

    // Oceania
    "Wellington": "Wellington",
    "Suva": "Suva",
    "Port Moresby": "Port Moresby",
    "Apia": "Ápia",
    "Nuku'alofa": "Nucualofa",
    "Funafuti": "Funafuti",
    "Honiara": "Honiara",
    "Port Vila": "Port Vila",
    "Tarawa": "Taraua",
    "Palikir": "Palikir",
    "Yaren": "Yaren"
};

module.exports = {
    dicionarioCapitais
};
