const dicionarioIdiomas = {
    // África
    "Arabic": "Árabe",
    "French": "Francês",
    "English": "Inglês",
    "Portuguese": "Português",
    "Swahili": "Suaíli",
    "Somali": "Somali",
    "Afrikaans": "Africâner",
    "Tswana": "Tswana",
    "Shona": "Xona",
    "Zulu": "Zulu",

    // Américas
    "Spanish": "Espanhol",
    "Portuguese": "Português",
    "English": "Inglês",
    "French": "Francês",
    "Dutch": "Holandês",
    "Haitian Creole": "Crioulo Haitiano",

    // Ásia
    "Mandarin Chinese": "Chinês (Mandarim)",
    "Hindi": "Hindi",
    "Bengali": "Bengali",
    "Urdu": "Urdu",
    "Nepali": "Nepalês",
    "Pashto": "Pachto",
    "Persian (Farsi)": "Persa (Farsi)",
    "Turkish": "Turco",
    "Hebrew": "Hebraico",
    "Malay": "Malaio",
    "Sinhala": "Cingalês",
    "Tamil": "Tâmil",
    "Khmer": "Khmer",
    "Lao": "Laosiano",
    "Thai": "Tailandês",
    "Burmese": "Birmanês",
    "Mongolian": "Mongol",
    "Kazakh": "Cazaque",
    "Uzbek": "Uzbeque",
    "Georgian": "Georgiano",
    "Armenian": "Armênio",
    "Korean": "Coreano",
    "Japanese": "Japonês",

    // Europa
    "German": "Alemão",
    "French": "Francês",
    "Italian": "Italiano",
    "Spanish": "Espanhol",
    "Portuguese": "Português",
    "English": "Inglês",
    "Dutch": "Holandês",
    "Danish": "Dinamarquês",
    "Norwegian": "Norueguês",
    "Swedish": "Sueco",
    "Finnish": "Finlandês",
    "Estonian": "Estoniano",
    "Latvian": "Letão",
    "Lithuanian": "Lituano",
    "Polish": "Polonês",
    "Czech": "Tcheco",
    "Slovak": "Eslovaco",
    "Hungarian": "Húngaro",
    "Greek": "Grego",
    "Romanian": "Romeno",
    "Bulgarian": "Búlgaro",
    "Serbian": "Sérvio",
    "Croatian": "Croata",
    "Slovene": "Esloveno",
    "Macedonian": "Macedônio",
    "Albanian": "Albanês",
    "Russian": "Russo",
    "Belarusian": "Bielorrusso",
    "Ukrainian": "Ucraniano",

    // Oceania
    "English": "Inglês",
    "Maori": "Maori",
    "Samoan": "Samoano",
    "Tongan": "Tonganês",
    "Bislama": "Bislama",
    "Kiribati": "Kiribatiano",
    "Palauan": "Palauano",
    "Nauruan": "Nauruano",
    "Fijian": "Fijiano",
    "Tok Pisin": "Tok Pisin",
    "Hiri Motu": "Hiri Motu"
};

module.exports = {
    dicionarioIdiomas
};
